### ISSUE TITLE
Unhelpful stack traces

### ISSUE THREAD

**Issue by mmower** [jakemcc/lein-autoexpect#12]
Hi.

So I quite often seem to get things like this:

**************\* Running tests ***************
Error refreshing environment: java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IFn
Tests completed at 14:16:25.933

where I'm left to guess where the problem has occurred. I end up having to fire up a REPL and try to recreate tests until I can locate what's breaking.

Any ideas?

Matt

**Comment by ricardoekm** [comment]
Hi I have the same issue here,
When this happen I need to go to REPL, execute the code, and print *e.

If autoexpect could print the stack trace of the exception would be very helpful. Currently it only print the exception message and the line in the test who originated the exception. So we have to chase what line in the code went wrong.

**Comment by jakemcc** [comment]
Guessing that you see this when there is an exception reloading a namespace
that is caused by come code being executed outside if an expect statement?

Having more if the exception print if there is an error refreshing the code
seems reasonable.

I'm traveling for a week or so but can look into changing this in early
October.

**Comment by jakemcc** [comment]
@ricardoekm Released `lein-autoexpect "1.7.0"` that prints the root cause of the stacktrace when there is a problem when reloading.

**Comment by ricardoekm** [comment]
Works like a charm! Thanks @jakemcc !
